language: java

sudo: required

env:
  matrix:
    - ENGINE=lucee@4.5
    - ENGINE=lucee@5
    - ENGINE=adobe@2016
    - ENGINE=adobe@11
    - ENGINE=adobe@10

cache:
  directories:
  - $HOME/.CommandBox

before_install:
  - sudo apt-key adv --keyserver keys.gnupg.net --recv 6DA70622
  - sudo echo "deb http://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a
    /etc/apt/sources.list.d/commandbox.list

install:
  - sudo apt-get update && sudo apt-get --assume-yes install commandbox
  - box install

before_script:
  - box server start cfengine=$ENGINE port=8500 openbrowser=false

script: >
  testResults="echo $(box testbox run reporter=mintext)";
  echo "$testResults";
  if grep -i "\[Failures: [1-9][0-9]\?[0-9]\?\]\|\[Errors: [1-9][0-9]\?[0-9]\?\]\|<t[^>]*>\|<b[^>]*>" <<< $testResults;  then exit 1; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c3bc8e90100d9446a065
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
